version: '3.8'


services:
  api:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go
    networks:
      - main-network
    depends_on:
      - mongo
    
  mongo:
    env_file:
      - .env
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    networks:
      - main-network

networks:
  main-network:
    driver: bridge