version: '3.8'


services:
  api:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go
    networks:
      - main-network
    depends_on:
      - db
      - mongo

  db:
    env_file:
      - .env
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - main-network
    
  mongo:
    env_file:
      - .env
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    networks:
      - main-network

networks:
  main-network:
    driver: bridge